version: '3.8'
services:
  web:
    image: clemzer/pff:latest
    networks:
      - overlay
    ports:
      - "1480:80"
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  overlay:
    driver: overlay
